FROM ubuntu
MAINTAINER haililihai <haililihai@gmail.com>

RUN apt-get update -qqy
RUN apt-get -qqy --no-install-recommends install \
	x11vnc xvfb fluxbox

# 生成Hash过的密码文件
RUN mkdir -p ~/.vnc \
	&& x11vnc -storepasswd hahaha ~/.vnc/passwd

RUN apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/list/*

# 屏蔽交互界面
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# 屏幕尺寸和颜色深度
ENV SCREEN_WIDTH 1360
ENV SCREEN_HEIGHT 1020
ENV SCREEN_DEPTH 24

# 使用较大的Unix套接字编号
ENV DISPLAY :99.0

# 暴露VNC的端口
EXPOSE 5900

# 复制启动脚本
COPY entry_point.sh /opt/bin/entry_point.sh
RUN chmod +x /opt/bin/entry_point.sh

CMD ["/opt/bin/entry_point.sh"]
