FROM daocloud.io/ubuntu:14.04 
MAINTAINER haililihai <haililihai@gmail.com> 
 
USER root 
 
RUN echo "deb http://debian.ustc.edu.cn/ubuntu/ trusty main universe\n" > /etc/apt/sources.list \ 
   && echo "deb http://debian.ustc.edu.cn/ubuntu/ trusty-updates main universe\n" >> /etc/apt/sources.list 
RUN apt-get update -qqy 
 
RUN apt-get -qqy --no-install-recommends install curl wget 
 
RUN apt-get autoclean && \ 
    apt-get autoremove && \ 
    rm -rf /var/lib/apt/list/* 
 
RUN useradd haililihai --shell /bin/bash --create-home \ 
   && usermod -a -G sudo haililihai \ 
   && echo 'haililihai ALL = (ALL) NOPASSWD: ALL'>> /etc/sudoers \ 
   && echo 'haililihai:hahaha' | chpasswd
