# run a dockerized GUI gedit locally
# 
# docker run -d \
#    -v /tmp/.X11-unix:/tmp.X11-unix \
#    -e DISPLAY=unix$DISPLAY \
#    --name test_gui \
#     haililihai/gedit_gui \
#     gedit
#
# docker logs -f ${tag}


FROM haililihai/ubuntu-base

RUN apt-get update -qqy
RUN apt-get -y --no-install-recommends \
    install gedit \
    libcanberra-dev \
    && rm -rf /var/lib/apt/list/*
    
RUN useradd -m not_root
USER not_root
